# Generated by Django 5.1.4 on 2025-01-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
        ('products', '0002_rename_produtc_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inflow',
            new_name='Outflow',
        ),
    ]
