# Generated by Django 5.1.4 on 2024-12-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtc',
            new_name='Product',
        ),
    ]
